name = "DesktopWindowManager"
uuid = "94386f1d-92c8-40aa-b9f2-763fabdcf2c5"
authors = ["Cédric Belmant"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
